# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ibm-apiconnect/pre-commit
    rev: 'main'
    hooks:
    -   id: validate-product
